server:
  port: 8091
  error:
    include-message: always
    include-binding-errors: always

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka
    region: default
    registryFetchIntervalSeconds: 5
  
logging:
  level:
    org:
      springframework:
        web: debug

spring:
  cloud:
    config:
      name: zipkin
      username: configUser
      password: configPassword
      discovery:
        service-id: config
        enabled: true